# Generated by Django 4.0.4 on 2022-06-04 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0005_user_email_user_name_user_phone_alter_user_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
