# Generated by Django 4.0.4 on 2022-06-04 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0007_user_alter_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
