# Generated by Django 4.0.4 on 2022-06-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0017_user_delete_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mail',
        ),
        migrations.AddField(
            model_name='user',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
