# Generated by Django 4.0.4 on 2022-06-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0019_task_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
