# Generated by Django 4.0.4 on 2022-06-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0020_task_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
